# Dockerfile
FROM nginx:alpine

# Copiar los archivos exportados de Next.js
COPY out/ /usr/share/nginx/html

# Copiar configuración personalizada de Nginx (opcional)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto 80
EXPOSE 3002

# Comando por defecto
CMD ["nginx", "-g", "daemon off;"]
