# Usamos una imagen base de Node.js
FROM node:18-alpine

# Crear y establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos del proyecto
COPY package.json package-lock.json ./

# Instalar las dependencias
RUN npm install --production

# Copiar todos los archivos del proyecto
COPY . .

# Construir la aplicación para producción
RUN npm run build

# Exponer el puerto en el que Next.js estará corriendo
EXPOSE 3002

# Comando para ejecutar la aplicación en producción
CMD ["npm", "start"]
